"""Ajout de comment_id avec clé étrangère nommée

Revision ID: 1a515757aa14
Revises: edaa6beb45cb
Create Date: 2025-02-17 20:17:21.662292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a515757aa14'
down_revision = 'edaa6beb45cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_reactions_comment', 'comments', ['comment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reactions_comment', type_='foreignkey')
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###
