"""Mise a jour de certains model

Revision ID: e249d49c9101
Revises: 982872ab6cc1
Create Date: 2025-02-10 22:55:00.826650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e249d49c9101'
down_revision = '982872ab6cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_shares', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
